-- MySQL Script generated by MySQL Workbench
-- 09/29/15 10:28:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zoo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zoo` ;

-- -----------------------------------------------------
-- Table `zoo`.`dyreart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`dyreart` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `navn` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`dyr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`dyr` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `navn` VARCHAR(45) NULL COMMENT '',
  `chipid` VARCHAR(45) NULL COMMENT '',
  `billede` VARCHAR(45) NULL COMMENT '',
  `fk_dyreart_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `chipid_UNIQUE` (`chipid` ASC)  COMMENT '',
  INDEX `fk_dyr_dyreart_idx` (`fk_dyreart_id` ASC)  COMMENT '',
  CONSTRAINT `fk_dyr_dyreart`
    FOREIGN KEY (`fk_dyreart_id`)
    REFERENCES `zoo`.`dyreart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zoo`.`dyrepasser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zoo`.`dyrepasser` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `navn` VARCHAR(45) NULL COMMENT '',
  `stilling` VARCHAR(45) NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `pw` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zoo`.`dyreart`
-- -----------------------------------------------------
START TRANSACTION;
USE `zoo`;
INSERT INTO `zoo`.`dyreart` (`id`, `navn`) VALUES (1, 'Hund');
INSERT INTO `zoo`.`dyreart` (`id`, `navn`) VALUES (2, 'Hest');
INSERT INTO `zoo`.`dyreart` (`id`, `navn`) VALUES (3, 'Gris');
INSERT INTO `zoo`.`dyreart` (`id`, `navn`) VALUES (4, 'Høns');

COMMIT;


-- -----------------------------------------------------
-- Data for table `zoo`.`dyr`
-- -----------------------------------------------------
START TRANSACTION;
USE `zoo`;
INSERT INTO `zoo`.`dyr` (`id`, `navn`, `chipid`, `billede`, `fk_dyreart_id`) VALUES (1, 'Caruso', '65433456', 'Caruso.jpg', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `zoo`.`dyrepasser`
-- -----------------------------------------------------
START TRANSACTION;
USE `zoo`;
INSERT INTO `zoo`.`dyrepasser` (`id`, `navn`, `stilling`, `username`, `pw`) VALUES (DEFAULT, 'Bengt Hoslt', 'Direktør', 'girafKiller', 'nukeemall');
INSERT INTO `zoo`.`dyrepasser` (`id`, `navn`, `stilling`, `username`, `pw`) VALUES (DEFAULT, 'Søren', 'Foderkarl', 's0ren', 'yesboss');

COMMIT;

